=== MykolaBova/Hib/julp/ProjectJulp-3.0.5/julp-search/build/classes/org/julp/search/julp-queries.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary indentification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/q3.dtd

--><!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE queries SYSTEM "q3.dtd">

    <queries>
    ...
    </queries>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT queries (query|executable)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT executable (#PCDATA)>
<!ATTLIST executable id CDATA #IMPLIED>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT query (order_by|having|group_by|adhoc_mappings|where|joins|from|ansi_join|select)*>
<!ATTLIST query
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT select (#PCDATA)>
<!ATTLIST select
    distinct CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ansi_join EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT from (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT joins (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT where (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT adhoc_mappings (adhoc)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT adhoc (tables|conditions|columns)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT columns (column)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT conditions (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT group_by (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT having (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT order_by (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT column (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tables (#PCDATA)>

=== MykolaBova/Hib/julp/ProjectJulp-3.0.5/julp-search/src/org/julp/search/q3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE queries SYSTEM "julp-queries.dtd">

<queries>
    
 <!-- If search column is PRODUCT.NAME than sql will have another JOIN:
 <tables>PRODUCT, ITEM</tables>
    <conditions>
     ITEM.INVOICE_ID = INVOICE.INVOICE_ID AND
     ITEM.PRODUCT_ID = PRODUCT.PRODUCT_ID AND
     INVOICE.TOTAL &gt; 6000
    </conditions>
 -->   
 <query id="customer1">
  <select distinct="true">
   CUSTOMER.CUSTOMER_ID,
   CUSTOMER.LAST_NAME,
   CUSTOMER.FIRST_NAME,
   CUSTOMER.PHONE,
   CUSTOMER.STREET,
   CUSTOMER.CITY,
   INVOICE.INVOICE_ID,
   INVOICE.TOTAL
  </select>
  <from>CUSTOMER, INVOICE</from>
  <where>
   CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID AND CUSTOMER.CUSTOMER_ID IS NOT NULL
  </where>
  <adhoc_mappings>
   <adhoc>   
    <columns> 
     <column>PRODUCT.NAME</column>  
    </columns> 
    <tables>PRODUCT, ITEM</tables>
    <conditions>
     ITEM.INVOICE_ID = INVOICE.INVOICE_ID AND
     ITEM.PRODUCT_ID = PRODUCT.PRODUCT_ID AND
     INVOICE.TOTAL &gt; 6000
    </conditions>
   </adhoc>
  </adhoc_mappings>
  <order_by>CUSTOMER.LAST_NAME, CUSTOMER.FIRST_NAME</order_by>
 </query>
 
 <query id="customer2">
  <ansi_join/> 
  <select distinct="true">     
   CUSTOMER.CUSTOMER_ID,
   CUSTOMER.LAST_NAME,
   CUSTOMER.FIRST_NAME,
   CUSTOMER.PHONE,
   CUSTOMER.STREET,
   CUSTOMER.CITY,
   INVOICE.INVOICE_ID,
   INVOICE.TOTAL
  </select>
  <from>CUSTOMER</from>
  <joins>
    INNER JOIN INVOICE ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
  </joins>
  <where>
   CUSTOMER.CUSTOMER_ID IS NOT NULL
  </where>
  <adhoc_mappings>
   <adhoc>
    <columns>
     <column>PRODUCT.NAME</column> 
    </columns>  
    <conditions>
     INNER JOIN ITEM ON INVOICE.INVOICE_ID = ITEM.INVOICE_ID
     INNER JOIN PRODUCT ON PRODUCT. PRODUCT_ID = ITEM. PRODUCT_ID AND
     INVOICE.TOTAL &gt; 6000
    </conditions>
   </adhoc>
  </adhoc_mappings>  
  <group_by>
  </group_by>
  <having>
  </having>
  <order_by>CUSTOMER.LAST_NAME, CUSTOMER.FIRST_NAME</order_by>
 </query>
</queries>

<!--
SELECT
   CUSTOMER.CUSTOMER_ID,
   CUSTOMER.LAST_NAME,
   CUSTOMER.FIRST_NAME,
   CUSTOMER.PHONE,
   CUSTOMER.STREET,
   CUSTOMER.CITY,
   INVOICE.INVOICE_ID,
   INVOICE.TOTAL,
   ITEM.ITEM,
   PRODUCT_ID,
   PRODUCT.NAME
FROM 
   CUSTOMER
        INNER JOIN INVOICE ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID  
        INNER JOIN ITEM ON INVOICE.INVOICE_ID = ITEM.INVOICE_ID
        INNER JOIN  PRODUCT ON  PRODUCT. PRODUCT_ID = ITEM. PRODUCT_ID AND
        INVOICE.TOTAL > 6000
WHERE 
   CUSTOMER.CUSTOMER_ID IS NOT NULL AND
   PRODUCT.NAME <> 'AAA'
ORDER BY CUSTOMER.CUSTOMER_ID,  INVOICE.INVOICE_ID, ITEM.ITEM
-->
